### ISSUE TITLE
Discuss need of explicit property definition of "uri" and "id"

### ISSUE THREAD

**Issue by sen542** [wzr1337/rsi.schema#11]
Brauchen wir id und uri wirklich in der Schema-Definition? Wie sehr ist es sinnvoll, diese properties wegzulassen, ob wohl sie später doch über den Draht gehen?

**Comment by wzr1337** [comment]
I translate to english:

Do we really need `id`and `uri`in the schema definition? How meaningful is it to remove those properties, even though we will transmit them "on the wire".

An I have to admit that I do not really understand the concern.

What do you mean by "explicit property definition of `uri` and `id`" ? 

Do you mean, because they are mandated by the spec anyway, we do not have to describe them for each and every object? Is the goal to simplify the schema definition file by removing all the `id` and `name` definitions when they are all the same anyway?

**Comment by sen542** [comment]
Yes, twice ;-) 
Correct translated. My idea was to omit these properties because they are mandated. But I'm not convinced if this idea is really a good one.  Probably it is better to have a complete description containing all the properties which may be sent on the wire.

**Comment by ghost** [comment]
Let's keep `id` and `uri` in the scheme, although their type is always the same at the moment. Hidden implicit details confuse.
If we remove `id` and `uri` from the schema, then people might start adding their own `id` and `uri` intended with special meaning.

**Comment by wzr1337** [comment]
Agreed, explicit definition also allows for easier generation of classes, documentation, diagrams etc. out of a given schema file
