### ISSUE TITLE
How to express filterability for GET, POST, PUT, DELETE

### ISSUE THREAD

**Issue by wzr1337** [wzr1337/rsi.schema#5]
In the Schema V1 we express filterability by providing 

``` json
...
endpoints: {
  "get": {
    "parameters: {
    <a map of all properties you can filter for>
    }
  }
}
...
```

This is:
1. failry implicit
2. does not apply to GET only 
3. has a different meaning for POST, PUT and DELETE

Actually, you could also do a POST request with query parameters, so we need a notation like:

``` json
...
endpoints: {
  "get": {
    "filterableBy" : [
    <a LIST of all property names you can filter for>
    ]
  }
}
...
```

The `filterableBy` property could then be used on all types of endpoints.

Any opinions?

**Comment by sen542** [comment]
"filterableBy" is very comprehensible. Then we should add more endpoints beside "get"; at least additional one for PUT and POST. Of course, "operation statements" for the request types should have a proper name because you should not filter by POST or PUT.
To answer wzr1337 question: yes, other opinions, because filterablyBy would puzzle the reader when applied to POST or PUT. (Personally I strongly recommend NOT to filter and post by the sme request.)

**Comment by wzr1337** [comment]
well..

if you 

```
POST /interieur/lights/?id=bcb869f1-5afe-4b0d-b864-d33f34295405,0ed151b0-a3d7-44ea-83eb-94290b2ca08c

{
  "color": "red"
}
```

you would want to set color for 2 elements synchronously, thus filter a list and apply the same POST to all of the selected entries with a single command, to keep all in sync. IN this case: avoid a "knigh rider effect" ;)

`filterableBy` is therefore also useful for POST

**Comment by sen542** [comment]
Filterability by _id_ is useful for POST and DELETE. One does not need other "filters" for these request types. Otherwise it would add additional (unnecessary) complexity. 
It is sufficient to receive all relevant element _id_ by applying GET and enumerate these _id_ in a second step request (e.g. POST to change several elements at the same time **or** DELETE several elements matching a certain filter criteria).
P.S. Of course filerting makes perfect sense for GET.

**Comment by ghost** [comment]
Is filterability always possible? Then we should only list exceptions.
I see it like Senior, POST and DELETE should not be filterable. REST is not SQL ;-)

**Comment by sen542** [comment]
OK, then we can now close this issue. Fibric and me refuse filterability on POST and DELETE. Several elements can be addressed at the same time by listing their IDs in the POST / DELETE request. So, the requirement is met and complexitity is not increased. (Now you'd need two requests; a first one to filter all the elements you want to modify/delete; a second one the modify/delete them.)
