### ISSUE TITLE
Get rid of the integer attribute type?

### ISSUE THREAD

**Issue by wzr1337** [wzr1337/rsi.schema#7]
Today, we are differentiating between numbers (floats) and integers. Is that really needed?

We got the `resolution` property for attribute definition if it is set to 1, the `number` automatically becomes a `integer`. 

I do not see any reason any more to keep `integer`.. does anyone?

**Comment by langmaack-fiolka** [comment]
As long as the `resolution` is a mandatory property I see no big issue in dropping the `integer` type. It maybe just adds a little bit more cognitive load to understand the API.

**Comment by ghost** [comment]
For C/C++, Java, or other strongly typed language code generators, it's maybe worth hinting them the exact type. But what level of detail is manageable and still easy to understand?

Floating numbers may need a `precision`/`resolution` information.
Integers/Floats could have a `minValue` and/or `maxValue`. Could also be `Infinity`.
Integers/Floats could have a `step` information. The `step` could also be an array of real numbers to describe curves.

I'm not sure if it's a good idea to add type information other than the official JSON types. If we do so, then we may quickly add not just C/C++ types but also CPU arch types (x32 or x64) and then ARM types because ARM uses Little Endian as opposed to while x86 CPUs use Big Endian and flips types around. RISC-V CPU is already threatening ARM CPU, so we are soon'ish forced to add another CPU arch related type of information.

I vote for recommending service manual authors to add pseudo type information in the service documentation instead of bloating the service schema.

**Comment by wzr1337** [comment]
Agree with both of you.. O will leave this open another week before we make a decision though..

Thank you very much for engaging!

**Comment by sen542** [comment]
I agree to all of you. Your reason are comprehensible and wise :-) I think your reasons are complete (nothing left to comment for me). 
But the, please nake "resolution" a mandatory setting for each numeric property.

**Comment by sen542** [comment]
Please be careful when defining "infinity". I think, it its better not to define an upper limit instead of infinity.

**Comment by wzr1337** [comment]
Sounds good .. I will build it the waye discussed

Thank you very much for your help

**Comment by wzr1337** [comment]
fixed with b9194a373ef18844c5317bacd2b8cca2b5a0876e
